### ISSUE TITLE
Support loading .jsx files

### ISSUE THREAD

**Issue by whastings** [jshanson7/babel-resolver#1]
I'm using React server-side so it would be nice if I could use babel-resolver with .jsx files. It seems you could either add .jsx to the built-in list of extensions to check or support the consuming app passing a list of extensions to check.

**Comment by jshanson7** [comment]
@whastings Good catch, I've added simple support for jsx.  Going forward I'm thinking of allowing an options map as the first argument:

``` javascript
require('babel-core/register')({
  presets: ['es2015'],
  resolveModuleSource: require('babel-resolver')({
    "resolveDirs": [__dirname],
    "resolveExtensions": [".js", ".jsx", ".json"]
  })
});
```

**Comment by whastings** [comment]
Thanks! I think an options map would be a good way to go.
